# Generated by Django 4.1.2 on 2023-04-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(choices=[('1', 'Tegan Hakim'), ('2', 'Tyler Lumpkin'), ('3', 'Outward Industries')], max_length=100)),
            ],
        ),
    ]
