# Generated by Django 4.1.2 on 2023-04-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outward', '0004_alter_learnpost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnpost',
            name='author',
            field=models.CharField(blank=True, choices=[('Tegan Hakim', 'Tegan Hakim'), ('Tyler Lumpkin', 'Tyler Lumpkin'), ('Outward Industries', 'Outward Industries')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learnpost',
            name='type',
            field=models.CharField(blank=True, choices=[('Web Design', 'Web Design'), ('Software', 'Software'), ('Business', 'Business')], max_length=100, null=True),
        ),
    ]
