# Generated by Django 4.1.2 on 2023-04-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outward', '0005_alter_learnpost_author_alter_learnpost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='learn_posts/images'),
        ),
    ]
